# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0002_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
