# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_user',
            name='interests',
            field=models.CharField(default=datetime.datetime(2017, 10, 18, 22, 0, 58, 29936, tzinfo=utc), max_length=3200),
            preserve_default=False,
        ),
    ]
