# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_reg_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_user',
            name='interests',
            field=models.CharField(default='', max_length=3200),
        ),
    ]
