# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-23 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20171018_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='eve_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Club_Name', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_Name', models.CharField(max_length=32)),
            ],
        ),
    ]
