# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_eve_detail_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_user',
            name='ConfirmPass',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
