# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-28 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_remove_reg_user_confirmpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_user',
            name='Name',
            field=models.CharField(default='John Snow', max_length=32),
            preserve_default=False,
        ),
    ]
