# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-31 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_reg_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
