# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-31 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20171031_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='eve_detail',
            name='HostSpeakers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eve_detail',
            name='Reviewedby',
            field=models.CharField(default='', max_length=3200),
        ),
        migrations.AddField(
            model_name='eve_detail',
            name='Reviews',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='eve_detail',
            name='UserRegistered',
            field=models.CharField(default='', max_length=3200),
        ),
        migrations.AddField(
            model_name='eve_detail',
            name='Venue',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='eve_detail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 31, 6, 17, 35, 491251, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eve_detail',
            name='interests',
            field=models.CharField(default='', max_length=3200),
        ),
        migrations.AddField(
            model_name='eve_detail',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='Club_Linked',
            field=models.CharField(default='', max_length=3200),
        ),
        migrations.AddField(
            model_name='tag',
            name='UserSubscribed',
            field=models.CharField(default='', max_length=3200),
        ),
    ]
