# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-03 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_reg_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg_Users',
        ),
    ]
